import { iRockContextType, iRockDataType } from "./Context";

export const blankDataStruct: iRockContextType = {
  tools: {
    drums: {
      drumsCurrentNum: [1, () => null],
      reset: [false, () => null],
      quaver: [false, () => null],
      and: [false, () => null],
    },
    keysCurrentNum: [1, () => null],
    currentSong: [null, () => {}],
    songList: [{}, () => {}],
  },
  section: {
    sectionName: ["string", () => null],
    chords: ["string", () => null],
    rhythm: {
      keys: {
        keySymbol1: ["blank", () => null],
        keySymbol2: ["blank", () => null],
        keySymbol3: ["blank", () => null],
        keySymbol4: ["blank", () => null],
        keySymbol5: ["blank", () => null],
        keySymbol6: ["blank", () => null],
        keySymbol7: ["blank", () => null],
        keySymbol8: ["blank", () => null],
        keySymbol9: ["blank", () => null],
        keySymbol10: ["blank", () => null],
        keySymbol11: ["blank", () => null],
        keySymbol12: ["blank", () => null],
        keySymbol13: ["blank", () => null],
        keySymbol14: ["blank", () => null],
        keySymbol15: ["blank", () => null],
        keySymbol16: ["blank", () => null],
      },
      guitar: {
        guitarSymbol1: ["blank", () => null],
        guitarSymbol2: ["blank", () => null],
        guitarSymbol3: ["blank", () => null],
        guitarSymbol4: ["blank", () => null],
        guitarSymbol5: ["blank", () => null],
        guitarSymbol6: ["blank", () => null],
        guitarSymbol7: ["blank", () => null],
        guitarSymbol8: ["blank", () => null],
        guitarSymbol9: ["blank", () => null],
        guitarSymbol10: ["blank", () => null],
        guitarSymbol11: ["blank", () => null],
        guitarSymbol12: ["blank", () => null],
        guitarSymbol13: ["blank", () => null],
        guitarSymbol14: ["blank", () => null],
        guitarSymbol15: ["blank", () => null],
        guitarSymbol16: ["blank", () => null],
      },
    },
    keys: {
      key1: ["", () => null],
      key2: ["", () => null],
      key3: ["", () => null],
      key4: ["", () => null],
      key5: ["", () => null],
      key6: ["", () => null],
      key7: ["", () => null],
      key8: ["", () => null],
      key9: ["", () => null],
      key10: ["", () => null],
      key11: ["", () => null],
      key12: ["", () => null],
      key13: ["", () => null],
      key14: ["", () => null],
      key15: ["", () => null],
      key16: ["", () => null],
      key17: ["", () => null],
      key18: ["", () => null],
      key19: ["", () => null],
      key20: ["", () => null],
      key21: ["", () => null],
      key22: ["", () => null],
      key23: ["", () => null],
      key24: ["", () => null],
    },
    drums: {
      drum1: ["", () => null],
      drum2: ["", () => null],
      drum3: ["", () => null],
      drum4: ["", () => null],
      drum5: ["", () => null],
      drum6: ["", () => null],
      drum7: ["", () => null],
      drum8: ["", () => null],
      drum9: ["", () => null],
    },
  },
};

export const blankSectionStruct: iRockDataType = {
  sectionName: "Enter section name",
  chords: "Enter chords",
  rhythm: {
    keys: {
      keySymbol1: "blank",
      keySymbol2: "blank",
      keySymbol3: "blank",
      keySymbol4: "blank",
      keySymbol5: "blank",
      keySymbol6: "blank",
      keySymbol7: "blank",
      keySymbol8: "blank",
      keySymbol9: "blank",
      keySymbol10: "blank",
      keySymbol11: "blank",
      keySymbol12: "blank",
      keySymbol13: "blank",
      keySymbol14: "blank",
      keySymbol15: "blank",
      keySymbol16: "blank",
    },
    guitar: {
      guitarSymbol1: "blank",
      guitarSymbol2: "blank",
      guitarSymbol3: "blank",
      guitarSymbol4: "blank",
      guitarSymbol5: "blank",
      guitarSymbol6: "blank",
      guitarSymbol7: "blank",
      guitarSymbol8: "blank",
      guitarSymbol9: "blank",
      guitarSymbol10: "blank",
      guitarSymbol11: "blank",
      guitarSymbol12: "blank",
      guitarSymbol13: "blank",
      guitarSymbol14: "blank",
      guitarSymbol15: "blank",
      guitarSymbol16: "blank",
    },
  },
  keys: {
    key1: "",
    key2: "",
    key3: "",
    key4: "",
    key5: "",
    key6: "",
    key7: "",
    key8: "",
    key9: "",
    key10: "",
    key11: "",
    key12: "",
    key13: "",
    key14: "",
    key15: "",
    key16: "",
    key17: "",
    key18: "",
    key19: "",
    key20: "",
    key21: "",
    key22: "",
    key23: "",
    key24: "",
  },
  drums: {
    drum1: "",
    drum2: "",
    drum3: "",
    drum4: "",
    drum5: "",
    drum6: "",
    drum7: "",
    drum8: "",
    drum9: "",
  },
};
