import { iRockContextType, iRockDataType } from "./Context";

export const blankDataStruct: iRockContextType = {
  tools: {
    currentSong: [null, () => {}],
    songList: [{ songList: {} }, () => {}],
  },
};

export const blankSectionStruct: iRockDataType = {
  sectionName: "Enter section name",
  chords: "e.g. F, Bb, Dm, C",
  voice: "e.g. Fargo 119",
  rhythm: {
    keys: {
      keySymbol1: "blank",
      keySymbol2: "blank",
      keySymbol3: "blank",
      keySymbol4: "blank",
      keySymbol5: "blank",
      keySymbol6: "blank",
      keySymbol7: "blank",
      keySymbol8: "blank",
      keySymbol9: "blank",
      keySymbol10: "blank",
      keySymbol11: "blank",
      keySymbol12: "blank",
      keySymbol13: "blank",
      keySymbol14: "blank",
      keySymbol15: "blank",
      keySymbol16: "blank",
    },
    guitar: {
      guitarSymbol1: "blank",
      guitarSymbol2: "blank",
      guitarSymbol3: "blank",
      guitarSymbol4: "blank",
      guitarSymbol5: "blank",
      guitarSymbol6: "blank",
      guitarSymbol7: "blank",
      guitarSymbol8: "blank",
      guitarSymbol9: "blank",
      guitarSymbol10: "blank",
      guitarSymbol11: "blank",
      guitarSymbol12: "blank",
      guitarSymbol13: "blank",
      guitarSymbol14: "blank",
      guitarSymbol15: "blank",
      guitarSymbol16: "blank",
    },
  },
  keys: {
    key1: [],
    key2: [],
    key3: [],
    key4: [],
    key5: [],
    key6: [],
    key7: [],
    key8: [],
    key9: [],
    key10: [],
    key11: [],
    key12: [],
    key13: [],
    key14: [],
    key15: [],
    key16: [],
    key17: [],
    key18: [],
    key19: [],
    key20: [],
    key21: [],
    key22: [],
    key23: [],
    key24: [],
    patch: [],
  },
  drums: {
    drum1: "",
    drum2: "",
    drum3: "",
    drum4: "",
    drum5: "",
    drum6: "",
    drum7: "",
    drum8: "",
    drum9: "",
  },
  guitar: {
    students: {
      student1: "Enter name",
      student2: "Enter name",
      student3: "Enter name",
    },
    string1: {
      fret1: [],
      fret2: [],
      fret3: [],
      fret4: [],
      fret5: [],
      fret6: [],
      fret7: [],
      fret8: [],
      fret9: [],
      fret10: [],
      fret11: [],
      fret12: [],
      fret13: [],
      fret14: [],
      fret15: [],
      fret16: [],
      fret17: [],
      fret18: [],
      fret19: [],
      fret20: [],
    },
    string2: {
      fret1: [],
      fret2: [],
      fret3: [],
      fret4: [],
      fret5: [],
      fret6: [],
      fret7: [],
      fret8: [],
      fret9: [],
      fret10: [],
      fret11: [],
      fret12: [],
      fret13: [],
      fret14: [],
      fret15: [],
      fret16: [],
      fret17: [],
      fret18: [],
      fret19: [],
      fret20: [],
    },
    string3: {
      fret1: [],
      fret2: [],
      fret3: [],
      fret4: [],
      fret5: [],
      fret6: [],
      fret7: [],
      fret8: [],
      fret9: [],
      fret10: [],
      fret11: [],
      fret12: [],
      fret13: [],
      fret14: [],
      fret15: [],
      fret16: [],
      fret17: [],
      fret18: [],
      fret19: [],
      fret20: [],
    },
    string4: {
      fret1: [],
      fret2: [],
      fret3: [],
      fret4: [],
      fret5: [],
      fret6: [],
      fret7: [],
      fret8: [],
      fret9: [],
      fret10: [],
      fret11: [],
      fret12: [],
      fret13: [],
      fret14: [],
      fret15: [],
      fret16: [],
      fret17: [],
      fret18: [],
      fret19: [],
      fret20: [],
    },
    string5: {
      fret1: [],
      fret2: [],
      fret3: [],
      fret4: [],
      fret5: [],
      fret6: [],
      fret7: [],
      fret8: [],
      fret9: [],
      fret10: [],
      fret11: [],
      fret12: [],
      fret13: [],
      fret14: [],
      fret15: [],
      fret16: [],
      fret17: [],
      fret18: [],
      fret19: [],
      fret20: [],
    },
    string6: {
      fret1: [],
      fret2: [],
      fret3: [],
      fret4: [],
      fret5: [],
      fret6: [],
      fret7: [],
      fret8: [],
      fret9: [],
      fret10: [],
      fret11: [],
      fret12: [],
      fret13: [],
      fret14: [],
      fret15: [],
      fret16: [],
      fret17: [],
      fret18: [],
      fret19: [],
      fret20: [],
    },
  },
};
